<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="2145263">

<title>Final405report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="2145263report_files/libs/clipboard/clipboard.min.js"></script>
<script src="2145263report_files/libs/quarto-html/quarto.js"></script>
<script src="2145263report_files/libs/quarto-html/popper.min.js"></script>
<script src="2145263report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2145263report_files/libs/quarto-html/anchor.min.js"></script>
<link href="2145263report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2145263report_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2145263report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2145263report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2145263report_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final405report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>2145263 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Near-surface wind plays a central role in controlling the transport of air pollutants, heat and moisture in the lower atmosphere. At many environmental monitoring sites, wind is recorded as long time series of speed and direction, which are difficult to interpret without appropriate statistical tools and visualisation. Wind rose diagrams have therefore become a standard way to summarise the joint distribution of wind speed and direction at a given location, and are widely used to identify prevailing wind sectors and their frequencies <span class="citation" data-cites="windros">(<a href="#ref-windros" role="doc-biblioref"><span>“Wind Roses - Charts and Tabular Data | NOAA Climate.gov,”</span> n.d.</a>)</span>.</p>
<p>Beyond overall frequency patterns, spatial and temporal variations in wind are also important for understanding surface–atmosphere exchanges. Flux footprint theory links eddy-covariance measurements at a tower to the upwind source area and shows that the origin of measured fluxes depends strongly on the wind field and atmospheric stability <span class="citation" data-cites="footprin">(<a href="#ref-footprin" role="doc-biblioref"><span>“Footprint Analysis for Measurements over a Heterogeneous Forest | Boundary-Layer Meteorology,”</span> n.d.</a>)</span>. A clear statistical description of wind regimes is therefore a prerequisite for interpreting environmental signals and evaluating how representative a site is for a heterogeneous landscape.</p>
<p>Recent advances in R-based tools make it possible to embed such statistical analyses in interactive web applications. The <strong>openair</strong> package provides a set of functions for analysing atmospheric and air-quality data in R, including wind roses and related directional plots <span class="citation" data-cites="carslaw2012">(<a href="#ref-carslaw2012" role="doc-biblioref">Carslaw and Ropkins 2012</a>)</span>. The <strong>Shiny</strong> framework turns R analyses into interactive web apps, where users can explore data through inputs such as file upload, selectors and sliders instead of fixed scripts <span class="citation" data-cites="chang2025">(<a href="#ref-chang2025" role="doc-biblioref">Chang et al. 2025</a>)</span>. This combination is particularly attractive for environmental science, because it couples reproducible statistical methods with flexible, user-driven exploration of monitoring data.</p>
<p>In this study, I develop an R Shiny application for the statistical analysis of a wind dataset containing time-stamped measurements of wind speed and direction. The app focuses on three related questions: (i) how often the wind blows from different sectors and at what speeds; (ii) how wind speed and direction vary over time; and (iii) whether simple statistical comparisons or trend models reveal systematic differences between wind sectors or temporal periods. To address these questions, the app integrates wind-rose visualisation, direction-frequency tables, wind-speed distributions and summary statistics, sector-wise hypothesis tests, and simple time-series trend models within a single interface. The goal is to provide a compact but extensible framework for exploring wind-related environmental data, and to demonstrate how Shiny can be used to bring statistical analysis and visualisation together in a transparent, reproducible way.</p>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="shiny-app" class="level3">
<h3 class="anchored" data-anchor-id="shiny-app">Shiny App</h3>
<section id="app-name-and-purpose" class="level4">
<h4 class="anchored" data-anchor-id="app-name-and-purpose">App name and purpose</h4>
<p>The application developed in this project is called <strong>“ENV405 wind analysis app”</strong>. Its goal is to provide an interactive environment for statistical analysis and visualization of hourly wind speed (<code>ws</code>) and wind direction (<code>wd</code>) data. Through a web-based interface, users can upload a CSV file or use the default <code>wind.csv</code> dataset, set wind-speed and wind-direction filters, and interactively explore wind roses, direction frequency distributions, wind-speed time series, wind-speed histograms, a footprint-style density plot, and grouped statistical tests.</p>
</section>
<section id="development-environment-and-dependencies" class="level4">
<h4 class="anchored" data-anchor-id="development-environment-and-dependencies">Development environment and dependencies</h4>
<p>The app was developed in R 4.x using a single <code>app.R</code> file. The main R packages are:</p>
<ul>
<li><code>shiny</code> for the web application framework<br>
</li>
<li><code>readr</code> for reading CSV files<br>
</li>
<li><code>dplyr</code> for data manipulation<br>
</li>
<li><code>lubridate</code> for parsing time stamps<br>
</li>
<li><code>openair</code> for wind-rose and air-quality style plots<br>
</li>
<li><code>ggplot2</code> for custom graphics<br>
</li>
<li>base R <code>stats</code> for t-tests and basic statistical methods</li>
</ul>
<p>As long as <code>app.R</code> and <code>wind.csv</code> are placed in the same working directory, the app can be run on different computers with the same package set.</p>
</section>
<section id="data-import-and-preprocessing" class="level4">
<h4 class="anchored" data-anchor-id="data-import-and-preprocessing">Data import and preprocessing</h4>
<p>On the server side a reactive object <code>wind()</code> controls data import. The logic is:</p>
<ul>
<li>If the user uploads a CSV file via <code>fileInput("file_wind")</code>, the app reads it with<br>
<code>read_csv(input$file_wind$datapath, show_col_types = FALSE)</code>.<br>
</li>
<li>Otherwise the app reads the local <code>wind.csv</code> file in the working directory.</li>
</ul>
<p>After reading, the app converts the <code>date</code> column to POSIXct using<br>
<code>mutate(date = ymd_hms(date))</code>, which is required for time-series plots.<br>
Wind direction in degrees (0–360) is mapped to eight sectors (N, NE, E, SE, S, SW, W, NW) by a helper function <code>wd_to_sector()</code>, which uses <code>cut()</code> to assign sector labels that are reused in later summaries and plots.</p>
</section>
<section id="user-interface-and-controls" class="level4">
<h4 class="anchored" data-anchor-id="user-interface-and-controls">User interface and controls</h4>
<p>The user interface is built with <code>fluidPage()</code> and <code>sidebarLayout()</code>:</p>
<ul>
<li>The <strong>sidebar panel</strong> contains the interactive controls:
<ul>
<li><code>fileInput</code> to upload an external wind dataset<br>
</li>
<li><code>sliderInput("ws_range")</code> to choose the range of wind speed to keep<br>
</li>
<li><code>selectInput("sector_filter")</code> to select “All” or a single wind sector<br>
</li>
<li><code>checkboxInput("show_points")</code> to toggle points on top of the wind-speed time series</li>
</ul></li>
<li>The <strong>main panel</strong> contains:
<ul>
<li>multiple <code>plotOutput</code> elements for the wind rose, direction frequency bar plot, wind-speed time series, wind-speed histogram, and footprint-style density plot<br>
</li>
<li><code>tableOutput</code> elements for the wind-direction frequency table and the wind-speed summary statistics<br>
</li>
<li>text outputs for a filter summary and the statistical test results</li>
</ul></li>
</ul>
</section>
<section id="core-reactive-structure-and-filtering" class="level4">
<h4 class="anchored" data-anchor-id="core-reactive-structure-and-filtering">Core reactive structure and filtering</h4>
<p>To keep the logic consistent across all outputs, the app defines a central reactive object <code>filtered_wind()</code>:</p>
<ol type="1">
<li>It starts from the data returned by <code>wind()</code>.<br>
</li>
<li>It filters observations according to the wind-speed range selected in <code>ws_range</code> and, if specified, the wind-direction sector chosen in <code>sector_filter</code>.<br>
</li>
<li>It returns the filtered data frame.</li>
</ol>
<p>All plots and tables (wind rose, direction frequency, time series, histogram, footprint density, and summary tables) are computed from <code>filtered_wind()</code>. This guarantees that all outputs reflect exactly the same filtering choices.</p>
</section>
<section id="statistical-analysis-module" class="level4">
<h4 class="anchored" data-anchor-id="statistical-analysis-module">Statistical analysis module</h4>
<p>For descriptive analysis, the app uses <code>summarise()</code> on <code>filtered_wind()</code> to compute basic wind-speed statistics: sample size, mean, median, minimum, maximum, and standard deviation. The results are displayed as the “Wind speed summary” table.</p>
<p>In addition, the app implements a two-sample t-test to compare mean wind speed between two wind sectors:</p>
<ul>
<li>The user selects <strong>Group A sector</strong> and <strong>Group B sector</strong> from two drop-down menus.<br>
</li>
<li>The server extracts the corresponding subsets of <code>filtered_wind()</code>, constructs a two-level factor for sector, and calls <code>t.test()</code> to test for a difference in mean <code>ws</code>.<br>
</li>
<li>The output shows sample sizes, mean wind speeds, the difference in means, the t statistic, and the p-value in text form, so that these results can be discussed later in the Quarto report.</li>
</ul>
</section>
<section id="visual-outputs" class="level4">
<h4 class="anchored" data-anchor-id="visual-outputs">Visual outputs</h4>
<p>The visualization components are:</p>
<ul>
<li><code>openair::windRose()</code> to display the joint distribution of wind speed and direction.<br>
</li>
<li><code>ggplot2</code> bar plots for relative frequency of wind sectors, line (and optional point) plots for the wind-speed time series, and histograms for the wind-speed distribution.<br>
</li>
<li>A footprint-style density map where wind speed and direction are converted to Cartesian coordinates<br>
<code>x = ws * sin(wd * pi / 180)</code> and <code>y = ws * cos(wd * pi / 180)</code><br>
and visualized with <code>stat_density_2d_filled()</code>.</li>
</ul>
<p>Axis titles are set horizontally and consistently across all figures to improve readability and layout.</p>
</section>
<section id="data-export" class="level4">
<h4 class="anchored" data-anchor-id="data-export">Data export</h4>
<p>The app includes a <code>downloadHandler</code> that lets users export the currently filtered dataset:</p>
<ul>
<li>The file name includes a timestamp, for example <code>"filtered_wind_YYYYmmdd_HHMMSS.csv"</code>.<br>
</li>
<li>The exported file is exactly the data returned by <code>filtered_wind()</code>.</li>
</ul>
<p>This makes the app not only an exploration tool but also a generator of reusable filtered datasets for further analysis.</p>
</section>
<section id="use-of-ai-assistance-and-validation" class="level4">
<h4 class="anchored" data-anchor-id="use-of-ai-assistance-and-validation">Use of AI assistance and validation</h4>
<p>In this study we used <strong>ChatGPT as assistance</strong> to help design the overall Shiny structure, refine and simplify R code, design the filtering and statistical modules, and understand specific functions from <code>openair</code> and <code>ggplot2</code>.</p>
<p>Every AI-suggested code block was run step-by-step in RStudio and checked manually:</p>
<ul>
<li>Direction frequencies from <code>direction_freq()</code> were compared to raw counts from the data.<br>
</li>
<li>t-test results were verified by running <code>t.test()</code> directly on subsets of the data in the console.<br>
</li>
<li>The same <code>app.R</code> and <code>wind.csv</code> were tested on another computer to confirm reproducibility.</li>
</ul>
<p>Only code that produced correct, interpretable results and matched the course requirements was kept and committed to GitHub. AI served purely as a coding and explanation assistant; all statistical decisions and validations were made by the author.</p>
</section>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>The wind dataset used in this project is the teaching dataset <strong><code>wind.csv</code></strong> provided by the ENV405 instructor. It was distributed through the course Box folder, and all students downloaded the same file. Each row represents one hourly observation at a monitoring site, and the main variables are:</p>
<ul>
<li><code>date</code>: observation time (as a character string, later parsed to POSIXct in the app)<br>
</li>
<li><code>ws</code>: wind speed in m/s<br>
</li>
<li><code>wd</code>: wind direction in degrees (0–360)</li>
</ul>
<p>In the Shiny app, this <code>wind.csv</code> file is the default data source. If the user does not upload a new file, the app reads <code>wind.csv</code>, parses the time stamps, and assigns wind sectors. If the user uploads a custom dataset with the same structure, the same preprocessing steps are applied. This design ensures that the analysis in the report is based on a shared course dataset while still allowing the app to be reused with other wind datasets.!</p>
</section>
</section>
<section id="results-and-discussions" class="level2">
<h2 class="anchored" data-anchor-id="results-and-discussions">Results and Discussions</h2>
<p>Figure 1 shows the full Shiny app interface and the default settings. The left sidebar contains all interactive controls, including the wind‐speed range slider, wind sector filter, checkbox for showing points on the time series, the choice between linear and loess trend models, and the selectors for the two wind sectors used in the t test. On the right, the app displays the wind rose, wind direction frequency plot, wind speed time series, wind speed histogram, footprint‐style plot, and three summary tables (Table 1–3). This layout means that users can get an overview of the wind data, its directional structure, temporal variation, and statistical tests on a single page, which is the main design goal of the app.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="git@github.com:Neohouqing/Final-ENV405Assignment.git"><img src="fig/Figure%201.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Figure 1. Overview of the ENV405 wind analysis Shiny app interface, showing the file upload, wind speed range slider, wind sector filter, time-series options, trend model selector, download button and all default plots displayed on the main panel."></a></p>
</figure>
</div>
<figcaption>Figure 1. Overview of the ENV405 wind analysis Shiny app interface, showing the file upload, wind speed range slider, wind sector filter, time-series options, trend model selector, download button and all default plots displayed on the main panel.</figcaption>
</figure>
</div>
<p>The directional structure of the wind field is summarised by the wind rose (Figure 2) and the wind direction frequency bar plot (Figure 3) under the default settings (wind speed 0–20 m/s, all sectors). The wind rose shows that the most frequent sectors are South (S) and South–West (SW), followed by West (W), while North (N) and North–East (NE) occur less often. This pattern is quantified in the frequency table (Table 2): the relative frequency is about 24.40% for S, 18.40% for SW and 14.90% for W, but only 12.20% and 6.80% for N and NE. This indicates that the site is dominated by southerly and south–westerly winds during the observation period, while northerly winds are comparatively rare. Figure 3 visualises the percentages in Table 2 as bars, making the contrast between the tall bars for S and SW and the shorter bars for NE and NW very clear. This is useful in teaching when we want students to quickly identify the dominant wind directions.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%202.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2. Wind rose for the full dataset, summarising the joint distribution of wind speed and wind direction sectors; bar length indicates frequency and colour indicates wind speed classes.</figcaption>
</figure>
</div>
<p><strong>Table 1 Wind speed statistics</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean_ws</th>
<th style="text-align: right;">median_ws</th>
<th style="text-align: right;">min_ws</th>
<th style="text-align: right;">max_ws</th>
<th style="text-align: right;">sd_ws</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">64724</td>
<td style="text-align: right;">4.49</td>
<td style="text-align: right;">4.10</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">19.60</td>
<td style="text-align: right;">2.40</td>
</tr>
</tbody>
</table>
<p><strong>Table 2 Wind direction frequency table</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">direction_sector</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">total</th>
<th style="text-align: right;">rel_freq</th>
<th style="text-align: right;">rel_freq_percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: right;">7884</td>
<td style="text-align: right;">64724</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">12.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">NE</td>
<td style="text-align: right;">4401</td>
<td style="text-align: right;">64724</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">6.80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: right;">4719</td>
<td style="text-align: right;">64724</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">7.30</td>
</tr>
<tr class="even">
<td style="text-align: left;">SE</td>
<td style="text-align: right;">4789</td>
<td style="text-align: right;">64724</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">7.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: right;">15798</td>
<td style="text-align: right;">64724</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">24.40</td>
</tr>
<tr class="even">
<td style="text-align: left;">SW</td>
<td style="text-align: right;">11920</td>
<td style="text-align: right;">64724</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">18.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">W</td>
<td style="text-align: right;">9643</td>
<td style="text-align: right;">64724</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">14.90</td>
</tr>
<tr class="even">
<td style="text-align: left;">NW</td>
<td style="text-align: right;">5570</td>
<td style="text-align: right;">64724</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">8.60</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%203.png" class="img-fluid figure-img"></p>
<figcaption>Figure 3. Bar plot of wind direction frequency under the default settings, showing the relative percentage of observations in each direction sector (N, NE, E, SE, S, SW, W, NW).</figcaption>
</figure>
</div>
<p>The overall distribution and typical strength of wind speed are described by the wind speed time series (Figure 4), the wind speed histogram (Figure 5), and the global statistics table (Table 1). The time series in Figure 4 shows strong variations between 0 and 20 m/s from 1997 to 2004. High wind events above 15 m/s are relatively rare but appear throughout the whole period, without being confined to a single year. The histogram (Figure 5) has a single peak and a right–skewed shape: most observations lie between 2 and 6 m/s, and the tail above 10 m/s becomes gradually thinner. Table 1 gives the corresponding numerical summary: the sample size is 64,724; the mean wind speed is 4.49 m/s; the median is 4.10 m/s; the minimum is 0 m/s; the maximum is 19.60 m/s; and the standard deviation is 2.40 m/s. Taken together, these results suggest that the typical wind regime is of moderate strength, with a background of persistent low–to–medium wind speeds and occasional strong winds, and no obvious extreme high–wind anomaly.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%204.png" class="img-fluid figure-img"></p>
<figcaption>Figure 4. Wind speed time-series plot for all observations, displaying individual measurements through time to highlight short-term variability and data density.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%205.png" class="img-fluid figure-img"></p>
<figcaption>Figure 5. Histogram of wind speed for the full dataset, illustrating the overall distribution of wind speeds and the right-skewed shape with most values between about 2 and 7 m/s.</figcaption>
</figure>
</div>
<p>From a dispersion point of view, the footprint‐style plot (Figure 6) shows the “simple footprint” under the default data. The x-axis is the cross–wind distance, the y-axis is the along–wind distance, and the colour scale represents the estimated relative contribution density. Figure 6 shows that the highest contribution is concentrated close to the source in the downwind direction (within about 1–3 arbitrary units along the wind and 2–5 units in the cross–wind direction), and then spreads outward as a fan. This “high contribution near the source, gradual dilution further away” pattern is consistent with classical footprint model results: areas closer to the sensor and aligned with the main downwind direction contribute most to the measured flux. Under the default conditions, this indicates that the local wind structure creates a compact main contribution area, which is useful when discussing how representative the flux measurements are for the surrounding surface.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%206.png" class="img-fluid figure-img"></p>
<figcaption>Figure 6. Default footprint-style plot based on the full dataset, showing a simple bivariate density of along-wind and cross-wind distance in arbitrary units.</figcaption>
</figure>
</div>
<p>The Shiny app also allows comparison of mean wind speeds between different sectors. Table 3 reports the sample size, mean wind speed, and standard deviation for each sector. S and SW have the highest mean speeds, about 5.53 m/s and 5.57 m/s, whereas N and NW have lower mean speeds, about 3.28 m/s and 3.16 m/s. This directional difference is formally tested using a Welch two–sample t test (Figure 7). Under the default setting, Group A is N and Group B is S. The test returns a t statistic of about −82.18, degrees of freedom around 21,780, and a p-value smaller than 2.2×10⁻¹⁶. The 95% confidence interval for the difference in means does not include zero. Together with the sample means in Table 3 (3.28 m/s for N and 5.53 m/s for S), this leads to a clear conclusion: during the study period, the mean wind speed from the south is significantly higher than from the north, and the difference is both statistically and climatologically important. This shows that direction affects not only how often the wind blows (Table 2) but also how strong it is on average (Table 3), which matters for both wind–energy potential and dispersion risk assessment.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%207.png" class="img-fluid figure-img"></p>
<figcaption>Figure 7. Welch two-sample t-test output comparing mean wind speeds between two selected wind sectors (Group A and Group B) under the default sector choices.</figcaption>
</figure>
</div>
<p><strong>Table 3 Sector means and t-test</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">direction_sector</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean_ws</th>
<th style="text-align: right;">sd_ws</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: right;">7884</td>
<td style="text-align: right;">3.28</td>
<td style="text-align: right;">1.67</td>
</tr>
<tr class="even">
<td style="text-align: left;">NE</td>
<td style="text-align: right;">4401</td>
<td style="text-align: right;">4.11</td>
<td style="text-align: right;">1.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: right;">4719</td>
<td style="text-align: right;">3.87</td>
<td style="text-align: right;">1.67</td>
</tr>
<tr class="even">
<td style="text-align: left;">SE</td>
<td style="text-align: right;">4789</td>
<td style="text-align: right;">4.20</td>
<td style="text-align: right;">2.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: right;">15798</td>
<td style="text-align: right;">5.53</td>
<td style="text-align: right;">2.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">SW</td>
<td style="text-align: right;">11920</td>
<td style="text-align: right;">5.57</td>
<td style="text-align: right;">2.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">W</td>
<td style="text-align: right;">9643</td>
<td style="text-align: right;">3.82</td>
<td style="text-align: right;">2.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">NW</td>
<td style="text-align: right;">5570</td>
<td style="text-align: right;">3.16</td>
<td style="text-align: right;">1.71</td>
</tr>
</tbody>
</table>
<p>Temporal trends are analysed with the trend model options in the app. Figure 8 shows the default case with all sectors and a linear model. The fitted line is almost flat, and its slope is extremely close to zero. Although the p-value of the slope is near zero because of the very large sample size, the coefficient of determination r² is only about 0.002. This means that the linear trend explains very little of the variation; most of the variability comes from short–term and seasonal changes rather than a long-term monotonic increase or decrease. In other words, over 1997–2004 the wind speed at this site appears relatively stable when viewed at the long-term scale.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%208.png" class="img-fluid figure-img"></p>
<figcaption>Figure 8. Linear trend analysis of wind speed over time, with a fitted regression line superimposed on the time-series points and the corresponding model statistics reported in the app.</figcaption>
</figure>
</div>
<p>Figures 9–11 then illustrate what happens when the user changes the filter settings, showing how the interactive analysis can reveal more detailed patterns. Figure 9 presents an example configuration: the wind sector is filtered to NE, the trend model is switched from Linear to Loess, and the time–series points remain visible. Under this configuration, the loess trend in Figure 10 bends upwards and then downwards. NE wind speeds increase during the first part of the period, reach a local maximum in the middle years, and then slowly decline. This pattern is hidden in the overall data (Figure 8), where the effects of different sectors are averaged together. It only emerges after filtering by sector. This suggests that different directional subsets may have very different temporal behaviours, and that the combination of filtering and model choice in the Shiny app makes such direction-specific trend analysis straightforward.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%209.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9. Screenshot of the control panel after changing the filters to “NE” wind sector, enabling point display, and switching the trend model from “Linear” to “Loess”.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%2010.png" class="img-fluid figure-img"></p>
<figcaption>Figure 10. Loess-smoothed trend of wind speed over time for the NE sector only, corresponding to the settings in Figure 9 and revealing a non-linear temporal pattern.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/Figure%2011.png" class="img-fluid figure-img"></p>
<figcaption>Figure 11. Footprint-style plot recomputed under the adjusted settings (Figure 9), illustrating how the spatial density pattern of along-wind and cross-wind distance changes after filtering the data.</figcaption>
</figure>
</div>
<p>Changing the filters also affects the footprint shape. Compared with the default footprint (Figure 6), the footprint under NE–only conditions (Figure 11) shows a slightly shifted and more elongated high–contribution area with a more concentrated colour pattern. This suggests that, under NE winds, turbulent transport is focused along a narrower transport corridor with weaker lateral spread, whereas the mixed–sector footprint in Figure 6 is wider and more fan–shaped. By comparing Figures 6 and 11, users can directly see how conditioning on a single sector changes the footprint geometry. This is important for understanding how the representativeness of flux measurements depends on wind direction.</p>
<p>Finally, the three summary tables work together with the interactive filters as a bridge between visualisation and numerical analysis. Table 1 reports the global wind speed statistics under the current filter settings; Table 2 shows the frequency distribution of wind directions; and Table 3 supports comparisons of sector–specific means and the t test. The filter summary text (visible in Figure 1) reports the number of rows after filtering and the current wind‐speed range and sector, so the user always knows which subset of the data they are analysing. Overall, the Shiny app not only reproduces a standard set of wind analysis plots (Figures 2–6, 8, 10–11), but also embeds statistical inference (t tests and trend fitting) inside an interactive interface. This allows the full cycle of “display results – detect patterns – test hypotheses” to be completed directly in a web browser.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This study developed an interactive Shiny app to explore the ENV405 wind speed and wind direction dataset in a systematic way. Combining the wind rose, wind direction frequency bar plot and frequency table, the app shows that during the study period winds mainly came from the south, southwest and west, while north and northwest winds were less frequent. The wind speed histogram and descriptive statistics indicate that most wind speeds fall between 3–6 m/s with a right-skewed distribution; very high wind speeds occur but are rare. Sector-wise means and Welch two-sample t-tests reveal significant differences in mean wind speed among direction sectors: the south and southwest sectors have the highest mean speeds, whereas the north and northwest sectors are clearly lower, indicating strong directional heterogeneity in the wind field. Time-series and trend analyses suggest that for the full 1997–2004 period the linear trend slope is close to zero with a very small R², so there is no strong evidence for a monotonic change in wind speed; however, when users filter to specific sectors and switch to a loess model, they can observe non-linear patterns such as “increase then decrease” in selected subsets. Overall, the Shiny app not only visualizes the main statistical features and directional differences of wind speed and direction, but also demonstrates how choices of data subset and model (filters, trend options and t-tests) directly affect statistical conclusions, providing a flexible and useful platform for exploratory analysis and teaching of environmental data.</p>
</section>
<section id="ai-disclosure" class="level2">
<h2 class="anchored" data-anchor-id="ai-disclosure">AI disclosure</h2>
<p>In this study, I used ChatGPT in a limited and supporting way. First, during the Shiny App design stage, I had already decided to implement shared filters, time–series analysis, wind–direction frequency statistics, and two–sample t-tests. I then discussed these ideas with ChatGPT to confirm that the overall analysis plan was technically feasible and to check whether my implementation had obvious problems or redundancy. I also consulted some of its generic code examples when reviewing my own scripts. Based on this, I repeatedly modified and refactored the code structure myself, including building the <code>reactive()</code> structure, integrating the filtering logic, adjusting the appearance of the plots, and deciding how to display the t-test and trend–model results in the interface. A few specific code fragments (for example, some <code>ggplot2</code> calls and the combined use of <code>renderTable()</code> and <code>downloadHandler()</code>) were adapted and simplified after I had already written an initial version, but the overall functionality design and final implementation were planned and decided by me.</p>
<p>For data analysis and debugging, I mainly relied on the R programming and statistical skills learned in ENV405. I iteratively ran the code, examined error messages, compared console outputs with the Shiny plots, and checked back against the raw data and course materials when results looked suspicious. ChatGPT’s main role here was linguistic: it helped me polish the wording of some Git commit messages so that they read more clearly in English, and it provided light language editing for parts of the Quarto report after I had written the first draft. All statistical interpretations, figure descriptions, and final conclusions were written and checked by me; AI only offered limited assistance for confirming ideas and improving the clarity of my written English.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-carslaw2012" class="csl-entry" role="listitem">
Carslaw, David C., and Karl Ropkins. 2012. <span>“<span><em>Openair</em></span> <span></span> an r Package for Air Quality Data Analysis.”</span> <em>Environmental Modelling &amp; Software</em> 27-28 (January): 52–61. <a href="https://doi.org/10.1016/j.envsoft.2011.09.008">https://doi.org/10.1016/j.envsoft.2011.09.008</a>.
</div>
<div id="ref-chang2025" class="csl-entry" role="listitem">
Chang, Winston, Joe Cheng, J. J. Allaire, Carson Sievert, Barret Schloerke, Yihui Xie, Jeff Allen, et al. 2025. <em>Shiny: Web Application Framework for r</em>. <a href="https://cran.r-project.org/web/packages/shiny/index.html">https://cran.r-project.org/web/packages/shiny/index.html</a>.
</div>
<div id="ref-footprin" class="csl-entry" role="listitem">
<span>“Footprint Analysis for Measurements over a Heterogeneous Forest | Boundary-Layer Meteorology.”</span> n.d. <a href="https://link.springer.com/article/10.1023/A:1002702810929">https://link.springer.com/article/10.1023/A:1002702810929</a>.
</div>
<div id="ref-windros" class="csl-entry" role="listitem">
<span>“Wind Roses - Charts and Tabular Data | NOAA Climate.gov.”</span> n.d. <a href="https://www.climate.gov/maps-data/dataset/wind-roses-charts-and-tabular-data">https://www.climate.gov/maps-data/dataset/wind-roses-charts-and-tabular-data</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>